name: llm-memory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai==1.3.9
      - chromadb==0.4.20
      - python-dotenv==1.0.1
      - tiktoken==0.5.1
      - nltk==3.8.1
